import type {
  BootstrapViewModel,
  MessageAttachment,
  Member,
  VoiceParticipant,
  Workspace,
} from "./models";

// Browser-only preview content. The Tauri bridge uses the native bootstrap
// response, so this local asset never becomes a production/backend attachment.
const mockImageAttachment: MessageAttachment = {
  id: "mock-attachment-liquid-glass",
  filename: "liquid-glass-preview.svg",
  contentType: "image/svg+xml",
  size: 1973,
  url: "/mock/attachment-preview.svg",
  width: 1200,
  height: 800,
  animated: false,
};

export const members: Member[] = [
  {
    id: "erix",
    name: "Erix",
    handle: "erix",
    initials: "ER",
    color: "#3ecf8e",
    presence: "online",
  },
  {
    id: "marin",
    name: "Marin",
    handle: "marin",
    initials: "MA",
    color: "#f05a38",
    presence: "online",
  },
  {
    id: "kasper",
    name: "Kasper",
    handle: "kasper",
    initials: "KA",
    color: "#13a895",
    presence: "away",
  },
  {
    id: "ines",
    name: "Ines",
    handle: "ines",
    initials: "IN",
    color: "#ec1764",
    presence: "online",
  },
  {
    id: "otto",
    name: "Otto",
    handle: "otto",
    initials: "OT",
    color: "#b66aff",
    presence: "offline",
  },
];

const deployRoom: VoiceParticipant[] = [
  { memberId: "erix", state: "idle", note: "push to talk" },
  { memberId: "marin", state: "speaking", note: "speaking" },
  { memberId: "kasper", state: "muted", note: "muted" },
  { memberId: "ines", state: "speaking", note: "speaking" },
];

export const workspaces: Workspace[] = [
  {
    id: "0",
    ownerId: "erix",
    name: "Messages",
    initials: "DM",
    accent: "#69d7bd",
    permissionKeys: [],
    memberIds: ["marin"],
    directMessages: true,
    channels: [
      { id: "dm-marin", name: "Marin", kind: "text", unread: true },
    ],
    voiceRooms: [],
    unreadCount: 1,
  },
  {
    id: "halcyon",
    ownerId: "erix",
    name: "Halcyon",
    initials: "HA",
    accent: "#3ecf8e",
    permissionKeys: ["administrator", "create_invite", "manage_roles"],
    memberIds: ["erix", "marin", "kasper", "ines", "otto"],
    directMessages: false,
    unreadCount: 84,
    channels: [
      { id: "gateway", name: "gateway", kind: "text" },
      { id: "launch", name: "launch", kind: "text" },
      { id: "design", name: "design", kind: "text", unread: true },
      { id: "random", name: "random", kind: "text" },
    ],
    voiceRooms: [
      {
        id: "deploy-room",
        name: "Deploy Room",
        latencyMs: 32,
        encrypted: true,
        participants: deployRoom,
      },
      {
        id: "lounge",
        name: "Lounge",
        latencyMs: 29,
        encrypted: true,
        participants: [],
      },
    ],
  },
  {
    id: "orbit",
    ownerId: "marin",
    name: "Orbit",
    initials: "OR",
    accent: "#ff6b91",
    permissionKeys: [
      "create_invite",
      "view_member_list",
      "view_channel",
      "send_messages",
      "read_message_history",
      "connect",
      "speak",
    ],
    memberIds: ["erix", "marin", "kasper"],
    directMessages: false,
    unreadCount: 12,
    channels: [
      { id: "orbit-general", name: "general", kind: "text" },
      { id: "orbit-labs", name: "labs", kind: "text" },
    ],
    voiceRooms: [],
  },
  {
    id: "arc",
    ownerId: "erix",
    name: "Arc",
    initials: "AR",
    accent: "#3bd6bd",
    permissionKeys: ["administrator", "create_invite", "manage_roles"],
    memberIds: ["erix", "ines"],
    directMessages: false,
    channels: [{ id: "arc-general", name: "general", kind: "text" }],
    voiceRooms: [],
  },
];

export const mockBootstrap: BootstrapViewModel = {
  revision: 0,
  cacheRecovery: null,
  cacheProtection: {
    encrypted: true,
    cipher: "SQLCipher 4.6.1 · AES-256",
    keyStorage: "Operating-system credential vault",
  },
  currentUserId: "erix",
  activeWorkspaceId: "halcyon",
  activeChannelId: "gateway",
  activeVoiceRoomId: "deploy-room",
  connectionState: "connected",
  pendingOutbox: 0,
  workspaces,
  members,
  relationships: [
    {
      userId: "marin",
      name: "Marin",
      handle: "marin",
      initials: "MA",
      color: "#f05a38",
      kind: "friend",
      since: "2026-07-27T17:24:00Z",
    },
    {
      userId: "ines",
      name: "Ines",
      handle: "ines",
      initials: "IN",
      color: "#ec1764",
      kind: "incoming",
      since: "2026-07-29T10:10:00Z",
    },
    {
      userId: "kasper",
      name: "Kasper",
      handle: "kasper",
      initials: "KA",
      color: "#13a895",
      kind: "outgoing",
      since: "2026-07-29T10:13:00Z",
    },
  ],
  typing: [],
  messages: [
    {
      id: "dm-1",
      channelId: "dm-marin",
      authorId: "marin",
      content: "The native DM path feels instant now.",
      sentAt: "13:58",
    },
    {
      id: "m-1",
      channelId: "gateway",
      authorId: "marin",
      content:
        "ok so the socket leak was us. classic\none listener never got removed on reconnect. fine until someone had wifi from 2009",
      sentAt: "14:02",
    },
    {
      id: "m-2",
      channelId: "gateway",
      authorId: "kasper",
      content: "lmao whose wifi",
      sentAt: "14:04",
    },
    {
      id: "m-3",
      channelId: "gateway",
      authorId: "marin",
      content: "otto’s hotel",
      sentAt: "14:04",
    },
    {
      id: "m-4",
      channelId: "gateway",
      authorId: "otto",
      content: "i am a stress test and you are all welcome",
      sentAt: "14:05",
      reactions: [{ emoji: "✅", count: 6 }],
    },
    {
      id: "m-5",
      channelId: "gateway",
      authorId: "erix",
      content: "is it deployed or do i need to not touch anything for an hour",
      sentAt: "14:09",
      reply: {
        author: "marin",
        text: "one listener never got removed on reconnect",
      },
    },
    {
      id: "m-6",
      channelId: "gateway",
      authorId: "marin",
      content: "deployed. touch whatever you want",
      sentAt: "14:10",
    },
    {
      id: "m-7",
      channelId: "gateway",
      authorId: "ines",
      content:
        "@erix look at this. 500 msgs, scrolled like a maniac, worst frame 11ms",
      sentAt: "14:24",
      attachments: [mockImageAttachment],
    },
    {
      id: "m-8",
      channelId: "gateway",
      authorId: "erix",
      content: "ok that’s actually good",
      sentAt: "14:26",
      delivered: true,
    },
    {
      id: "m-9",
      channelId: "gateway",
      authorId: "ines",
      content: "don’t jinx it",
      sentAt: "14:33",
      reactions: [{ emoji: "😅", count: 3 }],
    },
    {
      id: "m-10",
      channelId: "launch",
      authorId: "erix",
      content: "Release checklist is green. Keep the rollout boring.",
      sentAt: "12:40",
    },
    {
      id: "m-11",
      channelId: "design",
      authorId: "ines",
      content:
        "The horizontal channel rail is much calmer. Voice can stay contextual.",
      sentAt: "11:18",
    },
  ],
};
